#Setup ~~~
#Follow these 2 steps to set up your site.

#Step 1: give your study group a name and a short description,
#and choose a language from the options in the _data directory:
title: Humans Learning Machine Learning
description: "A group of physics trainees at the University of Toronto learning machine learning together."
language: en

#Step 2: press the green 'Commit Changes' button at the bottom of this page.

# That's it, your website is all set up!
# You can see it at https://YourUserName.github.io/studyGroup/
# No need to change anything below this line.
# To make your first event, check out the instructions at https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event
# Having trouble? Open a new issue at https://github.com/mozillascience/studyGroup/issues and we'll help you out ASAP!

# Optional Configuration
# None of these things need to be changed - but feel free!

titleBackground: "https://s3-us-west-2.amazonaws.com/webmaker-kits/learning%402x.jpg"
headlineSmall: "Welcome To Humans Learning Machine Learning!"
headlineMain: "Open to all humans... and machines"
logo: "img/logos/logo.png"

# Setup Google Calendar
# Usage:
# 1. create a new google account; set the calendar to 'public' (see https://support.google.com/calendar/answer/37083?hl=en on how to do this)
# 2. change 'USER' in the example urls below to the username of the google account you made for your calendar
# 3. set calendar_on: True.

calendar_on: True
calendar_embed_url: "https://calendar.google.com/calendar/embed?src=hlml.toronto%40gmail.com&ctz=America%2FToronto"
calendar_ical_url: "https://calendar.google.com/calendar/ical/hlml.toronto%40gmail.com/public/basic.ics"

# make pages for the _projects folder
collections:
  projects:
    output: true

#========================================
# No touching anything below this line :)
#========================================
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 87BCDE
  secondary: 004ebe
  secondary-dark: 00204e #pms655

# Build settings
markdown: kramdown
permalink: pretty
future: true
